services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: intellisales_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vega123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      DEBUG: "True"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
